-- USER SQL
CREATE USER htdemo IDENTIFIED BY 1234 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO htdemo ;
GRANT "RESOURCE" TO htdemo ;
ALTER USER htdemo DEFAULT ROLE "CONNECT","RESOURCE";